# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Configuration for ERC robots."""

import os

import isaaclab.sim as sim_utils

# from isaaclab.actuators import DCMotorCfg
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

##
# Configuration
##
NXP_DIR = "source/isaaclab_assets/data/Robots/ERC/Humanoids"
# Full Size Configuration [URDF]
NXP_V1_HUMANOID_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=os.path.join(
            os.getcwd(),
            NXP_DIR,
            "nxp_v1_humanoid/nxp_v1_humanoid.usd",
        ),
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.85),
        joint_pos={
            "left_hip_pitch_joint": 0.1309,
            "right_hip_pitch_joint": -0.1309,
            "left_hip_roll_joint": -0.0174,
            "right_hip_roll_joint": 0.0174,
            "left_hip_yaw_joint": -0.0872,
            "right_hip_yaw_joint": 0.0872,
            "left_knee_joint": -0.1745,
            "right_knee_joint": 0.1745,
            "left_ankle_pitch_joint": 0.0872,
            "right_ankle_pitch_joint": -0.0872,
            "left_ankle_roll_joint": -0.0174,
            "right_ankle_roll_joint": 0.0174,
            "left_shoulder_pitch_joint": 0.0000,
            "right_shoulder_pitch_joint": 0.0000,
            "left_shoulder_roll_joint": -0.0436,
            "right_shoulder_roll_joint": 0.0436,
            "left_shoulder_yaw_joint": -0.1309,
            "right_shoulder_yaw_joint": 0.1309,
            "left_elbow_joint": 0.1745,
            "right_elbow_joint": -0.1745,
            "torso_yaw_joint": 0.0000,
            "head_pan_joint": 0.0000,
            "head_tilt_joint": 0.0000,
        },
        # joint_pos={
        #     "left_hip_pitch_joint": 0.0,
        #     "right_hip_pitch_joint": 0.0,
        #     "left_hip_roll_joint": 0.0,
        #     "right_hip_roll_joint": 0.0,
        #     "left_hip_yaw_joint": 0.0,
        #     "right_hip_yaw_joint": 0.0,
        #     "left_knee_joint": 0.0,
        #     "right_knee_joint": 0.0,
        #     "left_ankle_pitch_joint": 0.0,
        #     "right_ankle_pitch_joint": 0.0,
        #     "left_ankle_roll_joint": 0.0,
        #     "right_ankle_roll_joint": 0.0,
        #     "left_shoulder_pitch_joint": 0.0,
        #     "right_shoulder_pitch_joint": 0.0,
        #     "left_shoulder_roll_joint": 0.0,
        #     "right_shoulder_roll_joint": 0.0,
        #     "left_shoulder_yaw_joint": 0.0,
        #     "right_shoulder_yaw_joint": 0.0,
        #     "left_elbow_joint": 0.0,
        #     "right_elbow_joint": 0.0,
        #     "torso_yaw_joint": 0.0,
        #     "head_pan_joint": 0.0,
        #     "head_tilt_joint": 0.0,
        # },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        # "torso": DCMotorCfg(
        #     joint_names_expr=["torso_yaw_joint"],
        #     effort_limit=17.0,
        #     saturation_effort=17.0,
        #     velocity_limit=33.93,
        #     stiffness=30.0,
        #     damping=1.5,
        #     armature=0.1,
        # ),
        # "hip_pitch": DCMotorCfg(
        #     joint_names_expr=[".*_hip_pitch_.*"],
        #     effort_limit=120.0,
        #     saturation_effort=120.0,
        #     velocity_limit=15.74,
        #     stiffness=200.0,
        #     damping=6.0,
        #     armature=0.1,
        # ),
        # "hip_roll": DCMotorCfg(
        #     joint_names_expr=[".*_hip_roll_.*"],
        #     effort_limit=200.0,
        #     saturation_effort=200.0,
        #     velocity_limit=15.74,
        #     stiffness=200.0,
        #     damping=6.0,
        #     armature=0.5,
        # ),
        # "hip_yaw": DCMotorCfg(
        #     joint_names_expr=[".*_hip_yaw_.*"],
        #     effort_limit=120.0,
        #     saturation_effort=120.0,
        #     velocity_limit=15.74,
        #     stiffness=200.0,
        #     damping=6.0,
        #     armature=0.1,
        # ),
        # "knee": DCMotorCfg(
        #     joint_names_expr=[".*_knee_.*"],
        #     effort_limit=200.0,
        #     saturation_effort=200.0,
        #     velocity_limit=15.74,
        #     stiffness=200.0,
        #     damping=6.0,
        #     armature=0.1,
        # ),
        # "ankle_pitch": DCMotorCfg(
        #     joint_names_expr=[".*_ankle_pitch_.*"],
        #     effort_limit=120.0,
        #     saturation_effort=120.0,
        #     velocity_limit=15.74,
        #     stiffness=200.0,
        #     damping=6.0,
        #     armature=0.1,
        # ),
        # "ankle_roll": DCMotorCfg(
        #     joint_names_expr=[".*_ankle_roll_.*"],
        #     effort_limit=120.0,
        #     saturation_effort=120.0,
        #     velocity_limit=15.74,
        #     stiffness=200.0,
        #     damping=6.0,
        #     armature=0.1,
        # ),
        # "arm": DCMotorCfg(
        #     joint_names_expr=[".*_shoulder_.*", ".*_elbow_.*"],
        #     effort_limit=17.0,
        #     saturation_effort=17.0,
        #     velocity_limit=33.93,
        #     stiffness=30.0,
        #     damping=1.5,
        #     armature=0.1,
        # ),
        # "head": DCMotorCfg(
        #     joint_names_expr=["head_.*"],
        #     effort_limit=14.0,
        #     saturation_effort=14.0,
        #     velocity_limit=24.50,
        #     stiffness=30.0,
        #     damping=1.5,
        #     armature=0.1,
        # ),
        "hip_pitch": ImplicitActuatorCfg(
            joint_names_expr=[".*_hip_pitch_.*"],
            effort_limit_sim=200.0,
            stiffness=200.0,
            damping=6.0,
            armature=0.1,
        ),
        "hip_roll": ImplicitActuatorCfg(
            joint_names_expr=[".*_hip_roll_.*"],
            effort_limit_sim=300.0,
            stiffness=300.0,
            damping=7.0,
            armature=0.1,
        ),
        "hip_yaw": ImplicitActuatorCfg(
            joint_names_expr=[".*_hip_yaw_.*"],
            effort_limit_sim=200.0,
            stiffness=200.0,
            damping=6.0,
            armature=0.1,
        ),
        "knee": ImplicitActuatorCfg(
            joint_names_expr=[".*_knee_.*"],
            effort_limit_sim=200.0,
            stiffness=200.0,
            damping=6.0,
            armature=0.1,
        ),
        "ankle_pitch": ImplicitActuatorCfg(
            joint_names_expr=[".*_ankle_pitch_.*"],
            effort_limit_sim=200.0,
            stiffness=200.0,
            damping=6.0,
            armature=0.1,
        ),
        "ankle_roll": ImplicitActuatorCfg(
            joint_names_expr=[".*_ankle_roll_.*"],
            effort_limit_sim=150.0,
            stiffness=150.0,
            damping=5.0,
            armature=0.1,
        ),
        "torso": ImplicitActuatorCfg(
            joint_names_expr=["torso_yaw_joint"],
            effort_limit_sim=30.0,
            stiffness=30.0,
            damping=1.0,
            armature=0.1,
        ),
        "shoulder_pitch": ImplicitActuatorCfg(
            joint_names_expr=[".*_shoulder_pitch_.*"],
            effort_limit_sim=30.0,
            stiffness=30.0,
            damping=1.0,
            armature=0.1,
        ),
        "shoulder_roll": ImplicitActuatorCfg(
            joint_names_expr=[".*_shoulder_roll_.*"],
            effort_limit_sim=30.0,
            stiffness=30.0,
            damping=1.0,
            armature=0.1,
        ),
        "shoulder_yaw": ImplicitActuatorCfg(
            joint_names_expr=[".*_shoulder_yaw_.*"],
            effort_limit_sim=30.0,
            stiffness=30.0,
            damping=1.0,
            armature=0.1,
        ),
        "elbow": ImplicitActuatorCfg(
            joint_names_expr=[".*_elbow_.*"],
            effort_limit_sim=30.0,
            stiffness=30.0,
            damping=1.0,
            armature=0.1,
        ),
        "head_pan": ImplicitActuatorCfg(
            joint_names_expr=["head_pan.*"],
            effort_limit_sim=20.0,
            stiffness=20.0,
            damping=0.5,
            armature=0.1,
        ),
        "head_tilt": ImplicitActuatorCfg(
            joint_names_expr=["head_tilt.*"],
            effort_limit_sim=20.0,
            stiffness=20.0,
            damping=0.5,
            armature=0.1,
        ),
    },
)
